### PR TITLE
Added typescript lib interface + Airbnb Eslint addition and fixes

### PR DESCRIPTION
**Pull request by omarryhan**
- Added Typescript lib interface (index.d.ts)
- Added Airbnb Eslint configs and recommendations.
- Auto fixed many lint errors
- Removed NodeJS v8 testing from Travis
- Added instructions for testing
- Tests now require a password when running locally (While still the same when running on Travis) I did that because both dbs refused to connect locally without a password
- Auto lint both examples
- Moved many functions out of the lib's main closure, to make the code more clear and enforce the purity of these functions. Only the Store class is what remains in the closure (Because it requires the session object)
- Added knex to main dependencies instead of dev dependencies.

Please squash my commits when merging, because some commits were more or less reverted and will confuse whoever looks back at them.

### CODE REVIEW

**Comment by omarryhan** [comment]
Also, I think we should create a `src` folder and split `index.js` into more than one file because it's a bit confusing with all the functions there. I thought it would be best to wait until you review this already big PR.

**Comment by llambda** [comment]
@omarryhan well done.

**Comment by llambda** [comment]
@omarryhan sorry I didn't seen your MR sooner. notifications can get rather cluttered on github :(

**Comment by omarryhan** [comment]
It's alright :)

**Comment by omarryhan** [comment]
Hey @llambda ,

Sorry to bother you again. Turns out there was a bug in this PR. Someone made a PR with a fix [here](https://github.com/llambda/connect-session-knex/pull/65). I merged it, then pushed a couple of other code organization chores and we're ready for a new release. Just thought I'd notify you with a ping, in case the notification didn't reach you.

**Comment by llambda** [comment]
Many thanks !!

**Pull request merged**
