### PR TITLE
Added Oracle as a supported DB in the Readme.me file and fixed a comment

### PR DESCRIPTION
**Pull request by bdwade100**
Hi Grant--

I made two minor changes:
- I added Oracle as a supported DB in the Readme.md file.
- I fixed a comment.

Let me know if you have any questions.

Thanks,
Brad Wade

### CODE REVIEW

**Comment by llambda** [comment]
Thanks! Would you please rebase your work into a single commit based on the latest master? (Right now I cannot merge it.)

**Comment by bdwade100** [comment]
Hi--

OK, I rebased my work based on your latest master.

Thanks,
Brad

**Comment by bdwade100** [comment]
I noticed that the tests failed. Not sure why--I only changed comments.

**Comment by bdwade100** [comment]
Hi Grant--

OK, the changes pass now. They should be ready to pull.

Thanks,
Brad

**Pull request merged**
